# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c446295321c34c2d3f09e4e713def9ffe7183bf5a70ea867b19153e0fb8e0d9b33d7ec325cdaf5d8bc9d842fa652dbaca9e90ff79b0727f0e23102a784d332

test:
  secret_key_base: 927b860abb69bfe3f08c30eb8d1522c4ef154ee93328df61d35950283dcf121e9e458404dce9ae67c36e2335e70c706eeb5403fe20520eaf04e077d11de7c17f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
